trigger: none

#pool:
  #vmImage: ubuntu-latest

#pool:
  #name: 'New SonarQube Integration Agent Pool'

#variables:
  #- template: variables-template.yml

variables:
  #- template: variables-template.yml
  - group: global-variables
  - group: vnet-variables
  - group: vm_variables
  - group: acr_variables
  - group: aks_variables
  - group: appgw_variables
  - group: db_variables

pool:
  vmImage: ubuntu-latest

stages:
- stage: create_vnet
  jobs:
  - job: create_vnet_job
    displayName: 'Create Virtual Network'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/virtual-network'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'vnet.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/virtual-network'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'

- stage: create_vm
  dependsOn: create_vnet
  jobs:
  - job: create_vm_job
    displayName: 'Create Virtual Machine'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/agent-vm'
        backendServiceArm: 'ARGOCD_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'vm.tfstate'
    - script: |
        sed -i 's/\r$//' script.sh
      displayName: 'Fix line endings'
      workingDirectory: '$(Build.SourcesDirectory)/agent-vm'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/agent-vm'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'

- stage: create_acr
  dependsOn: create_vm
  jobs:
  - job: create_acr_job
    displayName: 'Create Azure Container Registry'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/private-acr'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'acr.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/private-acr'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'
- stage: create_db
  jobs:
  - job: create_db_job
    displayName: 'Create Sql Server'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/sql-dbserver'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'db.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/sql-dbserver'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'ARGOCD_CONNECTION'
- stage: create_appgw
  #dependsOn: create_appgw
  jobs:
  - job: create_appgw_job
    displayName: 'Create Application Gateway'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/application-gateway'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'appgw.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/application-gateway'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'
- stage: create_aks
  #dependsOn: create_acr
  jobs:
  - job: create_aks_job
    displayName: 'Create Azure kubernetes services'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/private-aks'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'aks.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/private-aks'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'
- stage: destroy_aks
  #dependsOn: create_aks
  jobs:
  - job: destroy_aks_job
    displayName: 'Destroy Azure kubernetes'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/private-aks'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'aks.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/private-aks'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'
- stage: destroy_appgw
  #dependsOn: create_aks
  jobs:
  - job: destroy_appgw_job
    displayName: 'Destroy appgw'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/application-gateway'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'appgw.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/application-gateway'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'

- stage: destroy_acr
  #dependsOn: create_acr
  jobs:
  - job: destroy_acr_job
    displayName: 'Destroy Azure Container Registry'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/private-acr'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'acr.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/private-acr'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'
- stage: destroy_db
  jobs:
  - job: destroy_db_job
    displayName: 'destroy Sql Server'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/sql-dbserver'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'db.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/sql-dbserver'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'

- stage: destroy_vm
  #dependsOn: destroy_acr
  jobs:
  - job: destroy_vm_job
    displayName: 'Destroy Virtual Machine'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/agent-vm'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'vm.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/agent-vm'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'

- stage: destroy_vnet
  dependsOn: destroy_vm
  jobs:
  - job: destroy_vnet_job
    displayName: 'Destroy Virtual Network'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/virtual-network'
        backendServiceArm: 'SERVICE_CONNECTION'
        backendAzureRmResourceGroupName: 'Infra'
        backendAzureRmStorageAccountName: 'infradxostorage'
        backendAzureRmContainerName: 'dxo-demo-container'
        backendAzureRmKey: 'vnet.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/virtual-network'
        commandOptions: '-auto-approve -lock=false'
        environmentServiceNameAzureRM: 'SERVICE_CONNECTION'