# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

#pool:
  #vmImage: ubuntu-latest

pool:
  name: 'New SonarQube Integration Agent Pool'

variables:
  - template: variables-template.yml
  
steps:
  - template: Terraform-Install.yml
  - template: Terraform-Initialize.yml
  - template: Terraform-Validate.yml
  - template: Terraform-Plan.yml
  #- template: Terraform-Apply.yml
  - template: Terraform-Destroy.yml
  



 
  
        
  
   