resource_group_name     = "DSOKITTest"
location                = "East US"
service_principal_name = "DXO_TEST"
client_id              = ""
client_secret          = ""
name                     = "Demo-k8s-cluster-dev"
#environment              = "dev"