steps:
  - script: |
      echo "Setting TF_VAR_username environment variable..."
      export TF_VAR_client_id=""
      echo "TF_VAR_username set to $TF_VAR_username"
    displayName: 'Set TF_VAR_username Environment Variable'
